name: Go1.17

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  macos:
    name: Test Go1.17 for macOS
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Install gossa
      run: go install -v ./cmd/gossa

    - name: Go Test
      run: GOARCH=amd64 go test -race -v .

    - name: Test $GOROOT/test
      run: GOARCH=amd64 go run ./cmd/gossatest

  linux:
    name: Test Go1.17 for Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Install gossa
      run: go install -v ./cmd/gossa

    - name: Go Test amd64
      run: GOARCH=amd64 go test -race -v .

    - name: Test $GOROOT/test
      run: GOARCH=amd64 go run ./cmd/gossatest

  windows:
    name: Test Go1.17 for Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Install gossa
      run: go install -v ./cmd/gossa

    - name: Go Test amd64
      run: |
        set GOARCH=amd64
        go test -race -v .

    - name: Test $GOROOT/test amd64
      run: |
        set GOARCH=amd64 
        go run ./cmd/gossatest

    - name: Go Test 386
      run: |
        set GOARCH=386 
        go test -v .

    - name: Go $GOROOT/test 386
      run: |
        set GOARCH=386 
        go run ./cmd/gossatest
